name: ecorn
description: Ecorn flutter application


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  flutter_spinkit: ^4.1.2
  google_fonts: ^0.2.0
  dio: 3.0.9
  font_awesome_flutter: ^8.8.1
  google_maps_flutter: ^0.5.30
  location: ^3.0.2
  flutter_brand_icons: 1.1.0
  url_launcher: 5.4.5
  mask_text_input_formatter: 1.0.6
  flutter_datetime_picker: 1.4.0
  intl: 0.16.1
  flutter_email_sender: ^3.0.1
  geocoder: ^0.2.1
  geolocator: ^5.3.0
  flutter_google_places: ^0.2.5
  location_permissions: ^2.0.5
  localstorage: 3.0.2+5
  screen_loader: ^2.0.0
  auto_size_text: ^2.1.0
  connectivity: ^0.4.9+2
  bloc: ^6.0.3
  flutter_bloc: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.0.6
  mockito: ^4.1.2


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSans.ttf
    - family: CleanSans
      fonts:
        - asset: fonts/Cleanvel.ttf
    - family: Rubik
      fonts:
        - asset: fonts/OpenSans-Regular.ttf

